### PR TITLE
Complete implementation of weekdays early close

### PR DESCRIPTION
**Pull request by maread99**
Completes #247 implementation of regular early closes for specific weekdays.

- Adds documentation.
- Adds tests.
- Fixes precedence issue #253 so that if more than one description of special dates defines the same date,  time for that date will be assigned as earliest declared description.

### CODE REVIEW

**Comment by ValueRaider** [comment]
Great work. Give me a chance to run against some external tests I have, before you merge.

**Comment by maread99** [comment]
@ValueRaider, if you haven't any objections I'm going merge this and cut a new release...

**Comment by ValueRaider** [comment]
Go ahead with the merge, but consider #256 before a release.

**Comment by maread99** [comment]
@gerrymanoim, you happy for me to merge this one?

**Comment by gerrymanoim** [comment]
> @gerrymanoim, you happy for me to merge this one?

Yep - looks great to me. Thanks for grabbing this!

**Pull request merged**
