### PR TITLE
Add calendar for Kazakhstan AIXK exchange

### PR DESCRIPTION
**Pull request by pbabics**
Trading calendar for AIXK: https://www.aix.kz/trading/trading-calendar/
Hours: https://www.aix.kz/trading/trading-hours/

### CODE REVIEW

**Comment by maread99** [comment]
Great additions @pbabics!

Following the [most recent commit](https://github.com/gerrymanoim/exchange_calendars/commit/508d9fbef301e914d671b936ff09922653949322) these new calendars will need to have `adhoc_holidays` defined as timezone-naive (not UTC). You'll also at least need to add a test module for each to [tests](https://github.com/gerrymanoim/exchange_calendars/tree/master/tests) (e.g. test_aixk_calendar.py). The test module should include a subclass of [ExchangeCalendarTestBase](https://github.com/gerrymanoim/exchange_calendars/blob/508d9fbef301e914d671b936ff09922653949322/tests/test_exchange_calendar.py#L166). For examples, you may want to check out other test modules.

@gerrymanoim - hope I'm not overstepping the mark commenting here, but thought it reasonable in light of having been responsible for the changes to `adhoc_holidays`.

**Comment by pbabics** [comment]
Fixed

**Comment by gerrymanoim** [comment]
@maread99 - thanks for stepping in! Happy to add you as a collaborator to the repo if you'd like.

**Comment by gerrymanoim** [comment]
Thanks @pbabics !

**Comment by maread99** [comment]
@gerrymanoim - happy to be added as a collaborator, thanks for the offer. If you were to add me I'd let you know the type of permissions I would / would not be comfortable with exercising and perhaps in return you'd let me know of any restrictions that you would wish to be respected. My email address can be found [here](https://github.com/maread99) if you wanted to let me have an address to contact you on.

**Pull request merged**
