### PR TITLE
Add exchange calendar for Saudi Arabia XASU exchange

### PR DESCRIPTION
**Pull request by oldfishdk**
**Workflow to add a new Exchange Calendar**

It's recommended that whilst working through the process reference be made to existing calendar and test classes.

- [x] Add calendar module `exchange_calendars/exchange_calendar_{Exchange MIC}.py`. Module should contain a subclass of the abstract base class `ExchangeCalendar` (in `exchange_calendars/exchange_calendar.py`).
  - [x] Name subclass `{Exchange MIC}ExchangeCalendar`.
  - [x] Override methods and properties as required, being guided by ExchangeCalendar documentation and in-code comments. All abstract properties must be overriden.
  - [x] Include references / links for holidays and timings (either to class documentation or as comments).
- [x] Import calendar class to `exchange_calendars/calendar_utils.py` and add class to `_default_calendar_factories`. 
- [x] Add calendar test module `tests/test_{Exchange MIC}_calendar.py` Module should contain a subclass of the test base class `ExchangeCalendarTestBase` (in `tests/test_exchange_calendars.py`).
  - [x] Name subclass `Test{Exchange MIC}Calendar`.
  - [x] Override fixtures as required, being guided by ExchangeCalendarTestBase documentation and in-code comments. The `calendar_cls` and `max_session_hours` fixtures must be overriden.
- [x] Add a .csv file containing expected timings to `tests/resources/{Exchange MIC}.csv`. This file be generated by executing `python etc/make_exchange_calendar_test_csv.py {Exchange MIC}`. See script's documentation.
- [x] Add new exchange to Calendars table of README.md.
- [x] PR it!

### CODE REVIEW

**Comment by maread99** [comment]
Thanks for this @oldfishdk!

It's not passing the tests at the moment due to linting. If you could format the files to [black](https://github.com/psf/black) and it should pass.

Thanks again!

**Comment by oldfishdk** [comment]
Thanks for reviewing, I have just formatted the files and will watch for the CI

**Comment by maread99** [comment]
Thanks for the new calendar @oldfishdk!

**Comment by oldfishdk** [comment]
Also just wondering typically what is the release schedule? Or should I do anthing to release this change?

**Comment by maread99** [comment]
There's no schedule as such, rather we tend to cut releases as and when PRs have come in.

Just released [4.2.8](https://github.com/gerrymanoim/exchange_calendars/releases/tag/4.2.8) which includes the new XASU.

Thanks again.

**Pull request merged**
