### PR TITLE
Update xkls_holidays.py and xkls.csv

### PR DESCRIPTION
**Pull request by mrkgoh**
for Thaipusam, Deepavali and Yang Di-pertuan Agong's Birthday

### CODE REVIEW

**Comment by mrkgoh** [comment]
@gerrymanoim finally I think I got it right.

**Comment by mrkgoh** [comment]
@gerrymanoim , checks have passed.

**Comment by gerrymanoim** [comment]
Thanks!

**Comment by mrkgoh** [comment]
@gerrymanoim when will I be able pip install --upgrade with this commit?

**Comment by gerrymanoim** [comment]
Whenever we next cut a release. Should be soonish - but I'd like to get a few other PRs in this release.

**Comment by mrkgoh** [comment]
@gerrymanoim ok. I am using this library in my stock bot.

**Pull request merged**
