### PR TITLE
Correct xkls_holidays.py 2021

### PR DESCRIPTION
**Pull request by mrkgoh**
Update Muharram from "2021-08-09" to "2021-08-10"
Update Muhammad birthday from "2021-10-18" to "2021-10-19"

### CODE REVIEW

**Comment by gerrymanoim** [comment]
Hey @mrkgoh - changes LGTM. Do you have a source for this?

**Comment by mrkgoh** [comment]
@gerrymanoim , here is the source https://www.bursamalaysia.com/about_bursa/about_us/calendar

**Comment by gerrymanoim** [comment]
Thanks!

**Comment by mrkgoh** [comment]
Please release the next version.

**Pull request merged**
