### PR TITLE
Migrate from `pytz` to `zoneinfo`

### PR DESCRIPTION
**Pull request by maread99**
Migrates code base and tests from `pytz` to `zoneinfo`.

Also updates dependencies.

### CODE REVIEW

**Comment by maread99** [comment]
Tests **are** passing in 3.9. A single test, `test_trading_index`, is failing in 3.11. I'm unable to recreate the failure in a local 3.11 environment so I'm debugging via raising errors and inspecting the output in the GitHub workflow console (I can't get simple print statements to appear there??). Hence all the forced pushes.

The failure's odd. Something is resulting in the tz of the expected index to be set to a `pytz` timezone, but only in 3.11. and not in my local 3.11 environment. 🤷

**Comment by maread99** [comment]
The issue was with `pandas.read_csv`. 'Usually' this uses `datetime.timezone.utc` to represent the UTC timezone, although it would appear that `pytz.UTC` is used for certain combinations of pandas and python, including at least pandas 3.1.0 / py 3.11.5 (but not pandas 3,1.0 / py 3.11.0 or pandas 3.1.0 / py 3.9.13). Who knows what's going on under-the-bonnet.

**Comment by maread99** [comment]
@gerrymanoim this is good to go. If you're happy with it I'll merge it (and the other PR that's come in) and cut 4.4.

Closes #322.

Cheers.

**Comment by gerrymanoim** [comment]
LGTM. 

Did you do this manually? I've had good success using https://github.com/isidentical/refactor to do these types of large scale changes fyi.

**Comment by maread99** [comment]
package-wide Find and Replace for most of it and then just manually tidied up where usage was a little different. A lot less painful than I was expecting. Spent three times as long unearthing the inconsistent behaviour from `pd.read_csv`, a pita.

I'll merge and release tomorrow.

Thanks for the head up with the refactor package, I'll check it out.

**Comment by maread99** [comment]
Anticipate releasing under 4.4 early next week (w/c 23/09/11)...

**Pull request merged**
