### PR TITLE
Remove First president day from AIXK

### PR DESCRIPTION
**Pull request by romanzdk**

### CODE REVIEW

**Comment by maread99** [comment]
Hi @romanzdk, thanks for the PR.

Shouldn't the `start_date` remain so that this holiday isn't included pre 2013?

Also, would you have a reference?

Cheers

**Comment by romanzdk** [comment]
Fixed. 
https://aix.kz/trading/trading-calendar/

**Comment by romanzdk** [comment]
Tried to fix

**Comment by maread99** [comment]
Hi @romanzdk, the `non_holidays_sample` fixture still needs to include the last non-observance before the holiday started being observed, i.e. the 2012 date when this holiday would have otherwise fallen (2012/12/03 as 01 was a Saturday). This would ideally have been included when the holiday was first defined (the reason the tests were passing earlier with `start_date` removed was because this date hadn't been included). If you wouldn't mind adding it, otherwise this looks good to squash and merge.

Cheers

**Comment by romanzdk** [comment]
Added

**Comment by romanzdk** [comment]
Hmm.. test fails when I added this date 🤔

**Comment by maread99** [comment]
That's annoying. It's because the test calendar takes its dates from the answers file which for AIXK only goes back to 2017 (most go back to 1990 or 2010).

Up to you, either regenerate the answers file to start in 2010 (just pass `start` to the function that generates the answers' file) or take the "2012-12-01" date back out of the `non_holidays_sample` fixture and we'll leave it at that.

Sorry, if I'd have known the answer file was short I wouldn't have asked for the extra test date.

**Comment by maread99** [comment]
That'll explain it!

Thank you for the PR and the revisions @romanzdk. All merged.

**Pull request merged**
