### PR TITLE
XMOS: updated holidays from 2020 

### PR DESCRIPTION
**Pull request by iMikeBug**
Next changes to XMOS holidays were made:
1. Added 2 non-working days in June and July in 2020;
2. Added extension of holidays in May 2022. However, in csv file these days are still there.

**Workflow to modify an existing Exchange Calendar**

- [x] Modify calendar class as required. 
- [x] Modify the test resources file (e.g `tests/resources/{Exchange MIC}.csv`), either manually or by executing `python etc/make_exchange_calendar_test_csv.py {Exchange MIC}`.
- [x] Check if any of the fixtures in `tests/test_{Exchange MIC}_calendar.py` need updating to reflect your changes.
- [x] Add references to any new/modified holidays in `exchange_calendars/exchange_calendar_{Exchange MIC}.py`.

### CODE REVIEW

**Comment by maread99** [comment]
Thanks for the PR @iMikeBug, just looks like it needs linting to pass the tests. Cheers.

**Comment by iMikeBug** [comment]
I couldn't find info about whether there is function for creating working Saturday. During some years there are several Saturdays when Moscow Exchange operates the full day. 
Perhaps you can help to find this info?

**Comment by maread99** [comment]
Hi @iMikeBug, tests are failing, looks like the csv file doesn't fully reflect the changes made?

Separately, appears there's already dedicated lists for the 'labour_day_extensions' (L175) and 'victory_day_extensions' (L187). Could you place the corresponding holidays there rather than in the 'misc_adhoc' list. Thanks.

> I couldn't find info about whether there is function for creating working Saturday. During some years there are several Saturdays when Moscow Exchange operates the full day.

I suspect this wouldn't be trivial to implement. One messy option that occurs to me would be to change the `weekmask` property for the calendar to include Saturday and set up a holiday that would treat all Saturdays as holidays except those days when the market was open. Or something like that. There might well be better ways, possibly by effectively overriding the weekmask and somehow forcing in (adding) those Saturdays when the market was open. You'd need to dig into the code to work out what the options are I'm afraid.

**Comment by iMikeBug** [comment]
@maread99, thanks for your idea. Will try to implement it somehow. Maybe in another PR.
Hope that last commit will pass the tests)

**Comment by iMikeBug** [comment]
Saw the failed test. 
Frankly speaking, I don't understand the reason.
For example, my error is: AssertionError: assert Timestamp('2021-05-10 07:01:00+0000', tz='UTC') == Timestamp('2021-05-11 07:01:00+0000', tz='UTC')

I've added this day as a working day cause it didn't follow the rule. However, csv file didn't add this day as a working day.

**Comment by maread99** [comment]
I guess it's not as simple as the csv file needing to be updated again to reflect all the changes?

**Comment by iMikeBug** [comment]
@maread99 thanks for your help. Finally found my mistake.

**Comment by maread99** [comment]
Hi @iMikeBug. Sorry for not replying sooner.

Is it the case that you've manually amended the .csv file such that if in the future the script is run to automatically update the .csv the errors are going to raise again?  Thanks.

**Comment by iMikeBug** [comment]
Hi, @maread99. You're right. Unfortunately, I didn't understand the reason of this error. Calendar works correctly. But during .csv file generation working days are not added for several cases

**Comment by iMikeBug** [comment]
Oh, I've checked again. Everything is ok. .csv file is automatically generated without mistakes.

**Comment by maread99** [comment]
Thanks @iMikeBug, now merged into the master.

**Pull request merged**
