### PR TITLE
XTAE: fix wrong start time, add early Sunday close

### PR DESCRIPTION
**Pull request by ValueRaider**
The XTAE exchange is unusual:
1. Start and end times have tiny random variance, e.g. open either 9:59am or 10am. [Trading schedule](https://info.tase.co.il/eng/trading/trading_schedule/Pages/trading_schedule.aspx)
2. Sunday closes earlier

Most of these code change are to implement 2. I couldn't figure out a solution with `pandas.Holiday`, so modified the list of tuples `(time, HolidayCalendar)` to also accept `(time, Int)` where Int is day-of-week. This way can extend to other exchanges, although I didn't see any others with regular early closes.

Only other change is shifting open time from 10am to 9:59am ([relevant issue](https://github.com/gerrymanoim/exchange_calendars/issues/246))

### CODE REVIEW

**Comment by ValueRaider** [comment]
Benchmark slowdown must be from the changes to `exchange_calendar::scheduled_special_times()`. Is there a better way?

**Comment by gerrymanoim** [comment]
Apologies for the delay - I've been a bit busy lately. Will take a look at this this week.

**Comment by ValueRaider** [comment]
I've added another change for XTAE calendar - fixing a holiday. Makes sense to me to combine with this PR.

Noticed holiday problem when trading data wasn't quite matching calendar, now it's 100% match.

**Comment by maread99** [comment]
@gerrymanoim, @ValueRaider, no test here to cover the changes to `scheduled_special_times`? 🤨

**Comment by gerrymanoim** [comment]
My bad - should have caught that - appreciate the second pair of eyes. 

I actually think we can do this with a normal `Holiday` rule, will confirm.

**Comment by maread99** [comment]
> I actually think we can do this with a normal `Holiday` rule, will confirm.

My thoughts were the same. I had a look and thought it could be done by creating a `HolidayCalendar` with a `Holiday` for every day of the year with each having the `days_of_week` set as those weekdays with irregular times. This way a `HolidayCalendar` could be created which considers, for example, every Sunday as a holiday. **However**, as far as I can see the `Holiday` implementation doesn't provide for defining February 29 as a holiday - try and it'll error as it assumes all holidays must be annual. So, whenever the February 29 is a date with a 'special time' that irregular time wouldn't be registered.

Could offer pandas a PR pandas to improve `Holiday` to accommodate 29th February? Although, I think the real issue here is that `special_opens` and `special_closes` were implemented to define irregular times for annual 'holidays' rather than a weekly irregular time as the case is with XTAE. Weekly irregular times obviously need to be supported. I like @ValueRaider's approach to define them as special times with an `int` 👍, although if we're sticking with it then **the doc and signature types for `special_opens` and `special_closes` need to be updated to reflect this option**.

**Pull request merged**
