### PR TITLE
[XKRX] Update alternative holiday rule to match the revised law since 2021-08-04

### PR DESCRIPTION
**Pull request by elbakramer**
Since 2021-08-04, the alternative holiday rule for XKRX,
specifically the version which previously applied to Children's Day only, now also applies to the followings:

- Independence Movement Day (03-01)
- National Liberation Day (08-15) => actually we already missed one, which made 08-16 a holiday
- Korean National Foundation Day (10-03)
- Hangul Proclamation Day (10-09)

You can check these changes in any major calendar sites like:
https://www.timeanddate.com/holidays/south-korea/
(entries starting with "Day off for ...", I think they are wrong with the Christmas btw)

Other than major logic changes, there were some minor changes in tests so that all tests can pass:

- Setting `HAVE_BREAKS` to `False` although it actually has, because calendar now computes since `calendar.default_start` which is practically after year 2001 but XKRX does not have breaks after 2001. (Is this plausible? or should I make `default_start` older, at least for testing case only?)
- Limiting `end_date` s for some tests that check whether computed holidays fall into precomputed ones. Those tests were failing because more computed holidays are being added due to the changed alternative holiday rule but those are obviously not in the precomputed ones. I could add those added ones to precomputed list but was reluctant to do so since it would work like cheating tests that would check this new behavior.
- Limiting `start_date` s for some tests for similar reason. `default_start` was newer than the oldest one in precomputed answer csv file, so limted to check since then.

### CODE REVIEW

**Comment by maread99** [comment]
@gerrymanoim, @elbakramer, this seems to concern changes I made recently and will be further affected by anticipated changes to the test suite that will better accommodate breaks. I’m away at the moment although will pick this PR up towards the end of the month.

**Comment by maread99** [comment]
Having looked at the PR in more detail, this is the only question that concerns changes to the tests...

> Setting HAVE_BREAKS to False although it actually has, because calendar now computes since calendar.default_start which is practically after year 2001 but XKRX does not have breaks after 2001. (Is this plausible? or should I make default_start older, at least for testing case only?)

This is a problem with the test's limitations. It's anticipated that the HAVE_BREAKS constant will be withdrawn in favour of directly querying the csv file. In the meantime, keep HAVE_BREAKS set to False as you have done :thumbsup:

@gerrymanoim - I'll leave the rest of this with you given you reviewed @elbakramer's overhaul of this calendar a couple of months back.

**Comment by maread99** [comment]
@elbakramer, forgot to ask, why remove everything pre 2001-08-20 from the .csv file?

**Comment by elbakramer** [comment]
> @elbakramer, forgot to ask, why remove everything pre 2001-08-20 from the .csv file?

Had no intention, but just ran the following script to generate that csv file:
```
$ python etc/make_exchange_calendar_test_csv.py xkrx
```

**Comment by maread99** [comment]
Given the peculiarity of XKRX (historically having a break), I want to keep the period when the exchange had a break in the csv file (and hence covered by tests). The script narrowed the dates on the csv as a result of changes I recently made to default calendar dates. I didn't consider the implication for this script - sorry! I have just pushed a new version of the script which allows for defining start and end dates, and which by default takes the start date as the first date of any exisiting csv (all info in the revised doc).

Could I ask that you revise this PR so that the csv starts from '1986-01-04' (i.e. as previously). Easiest way might be to simply run the new script and commit the changes under a new commit (to override your previous changes).

**Comment by maread99** [comment]
Thanks @elbakramer, as [mentioned](https://github.com/gerrymanoim/exchange_calendars/pull/78#issuecomment-908699354), I'll leave the rest of this with @gerrymanoim.

**Pull request merged**
